### ISSUE TITLE
Pastas criadas para novas extensões usam a estrutura da v10 e não da v10.10

### ISSUE THREAD

**Issue by nunomsbranco** [PrimaverabssDeveloper/ExtensibilityEssentials#26]
Pastas criadas para novas extensões do ERP usam a estrutura da v10 - CommonExtensions ou pasta por empresa (ex.: DEMO) - e não a estrutura da v10.10 - pasta Extensions com subpasta para cada extensão.

Fará sentido manter temporariamente estes 2 funcionamentos em simultâneo, por exemplo mediante parâmetro nas configurações do Extensibility Essentials?

**Comment by nqueiros** [comment]
Não deveria... se há algum cenário em que isso aconteça então é um erro do produto e deverá ser reportado. A estrutura anterior é automaticamente convertida na nova no ato da migração, dado haver um comportamento distinto não é muito pacífico (nem será muito útil) colocá-lo dependente de uma configuração.

**Comment by nqueiros** [comment]
Ok, entendi mal :) 
Efetivamente o Essentials precisa de ser atualizado para ficar em conformidade com a nova estrutura de deployment das extensões (na realidade poderá ser simplificado).
Abraço

**Comment by Ssereno** [comment]
Sim é anomalia vou corriguir

**Comment by Ssereno** [comment]
Esta corrigido. Podes descarregar a nova verssão a partir deste artigo no developer network.COMO CONFIGURAR O AMBIENTE DE DESENVOLVIMENTO PARA AUTOMATIZAR O REGISTO DE EXTENSÕES?
