### ISSUE TITLE
Common Extension

### ISSUE THREAD

**Issue by pedrocarvalhal** [PrimaverabssDeveloper/ExtensibilityEssentials#28]
Boas,

Na configuração da extensão do visual studio, tenho a propriedade  "Common extension" a False a definido uma empresa,  quando executo o projeto e abro o ERP nas configuração da extensão do ERP aparece a comum a True, e não me aparece nenhuma empresa na minha extensão. 
No pasta do windows "C:\Program Files (x86)\PRIMAVERA\SG100\Config\LE\Extensions" aparece-me duas pastas uma com o nome da empresa que esta na configuração do visual studio e outra com o mome da DLL.
Embora esteja com a V10.10 e tendo eu associado á extensão outras dll's para alem de serem copiadas para a pasta das extensões tenho que copiar manualmente para a APL senão não consigo fazer debug.

**Comment by Ssereno** [comment]
Está corriguido e podes descarregar a correcção a partir do developer network neste artigo COMO CONFIGURAR O AMBIENTE DE DESENVOLVIMENTO PARA AUTOMATIZAR O REGISTO DE EXTENSÕES?
