### ISSUE TITLE
Não é possível usar o RegisterExtension.exe para automatizar o registo de extensões em ambientes multi-instância de ERP.

### ISSUE THREAD

**Issue by Tec26436** [PrimaverabssDeveloper/ExtensibilityEssentials#30]
Por faltar um parâmetro para se identificar a instância do ERP, não é possível usar o RegisterExtension.exe para automatizar o registo de extensões em ambientes multi-instância.

**Comment by Ssereno** [comment]
Trata-se de um bug. Vou tratar de corriguir.

**Comment by jonferreira** [comment]
Novidades?

**Comment by Ssereno** [comment]
Já tenho corriguido, mas ainda não valei os cenário de utilização.

**Comment by jonferreira** [comment]
Disponível para beta tester se quiseres

**Comment by Ssereno** [comment]
Está publicado. Podes fazer  download aqui neste artigo COMO CONFIGURAR O AMBIENTE DE DESENVOLVIMENTO PARA AUTOMATIZAR O REGISTO DE EXTENSÕES em https://developers.primaverabss.com/

**Comment by Ssereno** [comment]
Publicado

**Comment by jonferreira** [comment]
obrigado @Ssereno  vou testar. No entanto presumo que o Extensibility Essentials também terá de ser atualizado para suportar o /instance?

**Comment by jonferreira** [comment]
@Ssereno continuo com o erro "Sem licença para utilização de motores. A aplicação vai fechar"

Call "C:\Program Files\PRIMAVERA\SG100\APL\RegisterExtension.exe" DEMO jf XXXXXXXXXX 1 $(TargetPath) True 12345

**Comment by Ssereno** [comment]
Em analise

**Comment by jonferreira** [comment]
Qualquer informação adicional estou disponível.

**Comment by Ssereno** [comment]
Qual é a linha que tens instalada LE ou LP? se for LP podes me enviar o caminho da APL primavera.

**Comment by jonferreira** [comment]
@Ssereno viva. LP na pasta por defeito, c:\program files\Primavera\SG100

**Comment by Ssereno** [comment]
Está publicado novo binário.

Os parametros são passados nesta ordem
Company 
User 
Password 
ProductLine 
PathFileName 
CommonExtension 
Instance

**Comment by jonferreira** [comment]
teste rápido aparenta estar tudo OK vou testar melhor assim que possível e em caso de problemas avisa. Obrigado.

**Comment by jonferreira** [comment]
@Ssereno até ver tudo bem, podes fechar.

PS: creio que detetei um bug mas como não consigo confirmar se está relacionado com esta atualização vou criar novo issue
