### ISSUE TITLE
Versão do ficheiro não é atualizada no ERP quando o deploy é feito via RegisterExtension.exe

### ISSUE THREAD

**Issue by jonferreira** [PrimaverabssDeveloper/ExtensibilityEssentials#35]
### Describe the steps to reproduce

Compilar um dll com Assembly version e File version preenchido
Register extensão via RegisterExtension.exe

### The observed behavior

No ERP a versão do ficheiro é apresentada como 1.0.0.

### The expected behavior

No ERP a versão do ficheiro deveria ser igual ao File version do dll

### Environment

Plataforma V10.0010.0377
RegisterExtension.exe publicado em #30 

Ficheiro:
![image](https://user-images.githubusercontent.com/7714292/107363364-f2413180-6ad1-11eb-8318-8df39fe92ccb.png)

Registado via RegisterExtension.exe:
![image](https://user-images.githubusercontent.com/7714292/107363420-08e78880-6ad2-11eb-8d1c-dfbf759bad68.png)

Registado manualmente via ERP:
![image](https://user-images.githubusercontent.com/7714292/107363563-3cc2ae00-6ad2-11eb-82dd-c1ba8c4eac26.png)

**Comment by Ssereno** [comment]
Isso neste momento é o comportamento esperado.Vou ver a questão e ver faço correcção.

**Comment by jonferreira** [comment]
obrigado, agradeço pois assim é complicado de perceber que versão estamos a usar. seria importante também ter um parâmetro para passar a ordem em que queremos a .dll, atualmente tem de ser manualmente depois de importada via o utilitário.

**Comment by Ssereno** [comment]
Está publicada uma nova versão.

**Comment by jonferreira** [comment]
vou testar sergio, obrigado
