### ISSUE TITLE
Método ImprimeListagem não imprime documento com tabela DescVias (Agrupamento)

### ISSUE THREAD

**Issue by lordtitanium87** [PrimaverabssDeveloper/ExtensibilityEssentials#37]
ao imprimir um documento que não contenha a tabela descvias para o agrupamento das vias funciona na perfeição o código abaixo, no entanto se utilizar esta tabela o mapa ao ser gerado emite um erro que diz que a tabela não foi encontrada, de facto se formos a base de dados do ERP esta tabela não existe apenas existe no mapa em causa, será que falta passar algum parâmetro?

PSO.Mapas.Inicializar("VND");
                    strSelFormula = "{CabecDoc.NumDoc}='" + DocumentoVenda.NumDoc.ToString() + "' and ";
                    strSelFormula = "{CabecDoc.TipoDoc}='" + DocumentoVenda.Tipodoc + "' and";
                    strSelFormula = "{CabecDoc.Serie}='" + DocumentoVenda.Serie + "'";
                    PSO.Mapas.AddFormula("NomeLicenca", "'" + BSO.Licenca.Nome + "'");
                    strFormula = "StringVar CapitalSocial:='" + BSO.Contexto.ICCapitalSocial + "';";
                    strFormula = strFormula + "StringVar Morada:='" + BSO.Contexto.IDMorada + "';";
                    strFormula = strFormula + "StringVar Localidade:='" + BSO.Contexto.IDLocalidade + "';";
                    strFormula = strFormula + "StringVar CodPostal:='" + BSO.Contexto.IDCodPostal + "';";
                    strFormula = strFormula + "StringVar Telefone:='" + BSO.Contexto.IDTelefone + "';";
                    strFormula = strFormula + "StringVar Contribuinte:='" + BSO.Contexto.IFNIF + "';";
                    strFormula = strFormula + "StringVar Conservatoria:='" + BSO.Contexto.ICConservatoria + "';";
                    strFormula = strFormula + "StringVar Matricula:='" + BSO.Contexto.ICMatricula + "';";
                    strFormula = strFormula + "StringVar MoedaCapitalSocial:='" + BSO.Contexto.ICMoedaCapSocial + "';";
                    strFormula = strFormula + "StringVar Nome:='" + BSO.Contexto.IDNome + "'";
                    PSO.Mapas.SetFormula("DadosEmpresa", strFormula);
                    PSO.Mapas.SelectionFormula = strSelFormula;
                    PSO.Mapas.Destino =StdBSTipos.CRPEExportDestino.edNoExport;
                    PSO.Mapas.TipoFolha =StdBSTipos.CRPETipoFolha.tfA4;
                    PSO.Mapas.ImprimeListagem("GCPVSEC3", "Documento", "W", this.DocumentoVenda.NumVias, bMapaSistema: false, blnModal: true, sSelFormula: strSelFormula, sDocumento: "N");

**Comment by Ssereno** [comment]
Este não é local para este erro.  Aqui só devem ser reportados erros relacionados com este projecto.
