### ISSUE TITLE
Atualização de Addon para VS2022

### ISSUE THREAD

**Issue by brunobola** [PrimaverabssDeveloper/ExtensibilityEssentials#41]
Boa tarde, fiz diversas atualizações em dependências no projeto para ficar a funcionar no VS2022 também, e, entre outros melhoramentos, coloquei as referências como PackageReferences para melhor manutenção.

Criei o pull Request: #40

**Comment by Ssereno** [comment]
A new release will be published on may 19. Sorry by the delay on the pull request approval but I had to exclude the packages fix because it causes changes the build process. In the future maybe I implement that
