### ISSUE TITLE
When trying to add CustomTab in Visual Studio 2019 and 2022 it crashes the IDE

### ISSUE THREAD

**Issue by brunobola** [PrimaverabssDeveloper/ExtensibilityEssentials#48]
View image to see the problem.
![VS_CRASH_ADD_CUSTOMTAB_PRIMAVERA](https://user-images.githubusercontent.com/10889019/196156431-5f2fb3d8-7801-42cb-97bb-568af86cacf3.gif)

**Comment by Ssereno** [comment]
Olá Bruno creio que o problome está resolvido.
